/**:
  ros__parameters:
    product_name: LDLiDAR_LD19
    topic_name: scan
    model: ld19
    port_name: /dev/omnicar_lidar
    port_baudrate: 230400
    base_frame_id: base_footprint
    laser_frame_id: laser
    laser_pose_x: 0.09
    laser_pose_y: 0.0
    laser_pose_z: 0.0
    laser_pose_yaw: -90.0
    laser_pose_pitch: 0.0
    laser_pose_roll: 0.0
    dist_min: 0.02
    dist_max: 12.0
    laser_scan_dir: true
    enable_angle_crop_func: false
    angle_crop_min: 135.0
    angle_crop_max: 225.0
