product_name: "LDLiDAR_LD19"    # Assicurati che il main cerchi 'product_name'
topic_name: "scan"
model: "ld19"
serial_port_name: "/dev/ttyUSB1"
baud_rate: 230400
base_frame_id: "base_footprint"
laser_frame_id: "laser"
#base_frame_id: $(arg robot_id)/base_footprint
#laser_frame_id: $(arg robot_id)/laser
laser_pose_x: 0.09
laser_pose_y: 0.0
laser_pose_z: 0.0
laser_pose_yaw: -90.0
laser_pose_pitch: 0.0
laser_pose_roll: 0.0
dist_min: 0.02
dist_max: 12.0

laser_scan_dir: true
enable_angle_crop_func: false
